train:
	python3 NNG2P.py -l 1 -t 1 -s 1 -f -T

run:
	python3 NNG2P.py -l 4 -t 10 -s 10 -f -r 10000

use:
	python3 NNG2P.py -l 10 -t 1000 -s 1000 -n

kfold:
	python3 NNG2P.py -l 5 -k -f -r 5

kfold_use:
	python3 NNG2P.py -l 5 -n -k -f

clean:
	rm -rf read_data.p
	rm -rf phone_map.p
	rm -rf graph_map.p
	rm -rf neural_network.p
